import "./globals.css";
import { Providers } from "./providers.jsx";
import Header from "../components/Header.jsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-white dark:bg-black p-8">
        <Providers>
          <main className="dark:border-white border-black border-4 ease-in-out">
            <Header />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
